export const STORAGE_PREFIX = '@DGP:';
export const STORAGE_TOKEN_KEY = `${STORAGE_PREFIX}TOKEN`;
export const STORAGE_USER_KEY = `${STORAGE_PREFIX}USER`;
export const STORAGE_USER_PRODUCTS = `${STORAGE_PREFIX}USER_PRODUCTS`;
export const STORAGE_PRODUCT_SELECTED = `${STORAGE_PREFIX}PRODUCT_SELECTED`;
